Install more patched scripts

diff --git a/plexil.script-paths.patch b/plexil.script-paths.patch
--- a/plexil.script-paths.patch
+++ b/plexil.script-paths.patch
@@ -189,21 +189,28 @@ index 56fe9d0..159d51c 100644
    </target>
  
 diff --git a/scripts/checkPlexil b/scripts/checkPlexil
-index c313859..a8fdd71 100755
+index c313859..e952117 100755
 --- a/scripts/checkPlexil
 +++ b/scripts/checkPlexil
-@@ -42,21 +42,14 @@ then
+@@ -37,26 +37,19 @@
+ if [ -z "$PLEXIL_HOME" ]
+ then
+     echo Error: Please set environment variable PLEXIL_HOME
+-    echo to the full pathname of your 'plexil' or 'trunk' directory.
++    echo by loading /etc/profile.d/plexil.sh.
+     echo Exiting.
      exit 2
  fi
  
 -prog=${PLEXIL_HOME}/checker/global-decl-checker.jar
 +prog=/usr/share/java/plexil/global-decl-checker.jar
  args=$*
- JAVA=java
+-JAVA=java
 -if [ -n "$JAVA_HOME" ]
 -then
 -    JAVA=$JAVA_HOME/bin/java
 -fi
++JAVA=/usr/bin/java
  
  # Make sure jar file exists
  if [ ! -f "${prog}" ]
@@ -216,6 +223,66 @@ index c313859..a8fdd71 100755
    exit 2
  fi
  
+diff --git a/scripts/eplexil b/scripts/eplexil
+index 5ceeb0e..338b0a2 100755
+--- a/scripts/eplexil
++++ b/scripts/eplexil
+@@ -29,7 +29,7 @@
+ if [ -z "$PLEXIL_HOME" ]
+   then
+     echo Error: Please set environment variable PLEXIL_HOME
+-    echo to the full pathname of your 'plexil' or 'trunk' directory.
++    echo or make sure that /etc/profile.d/plexil.sh is loaded.
+     exit 1
+ fi
+ 
+@@ -46,10 +46,6 @@ if [ $# = 2 ]
+     exit 1
+ fi
+ 
+-JAVA=java
+-if [ -n "$JAVA_HOME" ]
+-then
+-    JAVA=$JAVA_HOME/bin/java
+-fi
++JAVA=/usr/bin/java
+ 
+-exec $JAVA -jar $PLEXIL_HOME/jars/saxon9he.jar -xsl:"$PLEXIL_HOME/schema/translate-plexil.xsl" -s:"$input_file" -o:"$output_file"
++exec $JAVA -jar /usr/share/java/saxon/Saxon-HE.jar -xsl:"$PLEXIL_HOME/schema/translate-plexil.xsl" -s:"$input_file" -o:"$output_file"
+diff --git a/scripts/plexil b/scripts/plexil
+index 941857c..6efcd45 100755
+--- a/scripts/plexil
++++ b/scripts/plexil
+@@ -33,26 +33,17 @@ if [ -z "$PLEXIL_HOME" ]
+     exit 1
+ fi
+ 
+-. $PLEXIL_HOME/scripts/plexil-setup.sh
+-
+-prog=${PLEXIL_HOME}/viewers/pv/luv.jar
++prog=/usr/share/java/plexil-viewer.jar
+ 
+ # Make sure executable exists.
+ if [ ! -e $prog ]
+   then
+-    echo Error: Plexil Viewer has not been built.
+-    echo You can build it with these commands:
+-    echo " cd ${PLEXIL_HOME}/viewers/pv"
+-    echo " ant jar"
++    echo Error: Could not find plexil viewer at $prog.
+     echo Exiting.
+     exit 1
+ fi
+ 
+-JAVA=java
+-if [ -n "$JAVA_HOME" ]
+-then
+-    JAVA=$JAVA_HOME/bin/java
+-fi
++JAVA=/usr/bin/java
+ 
+ if [ `uname` = "Darwin"  ]
+   then
 diff --git a/scripts/plexil.profile.sh b/scripts/plexil.profile.sh
 new file mode 100644
 index 0000000..7f90c6c
@@ -277,3 +344,87 @@ index f211fe1..e311b00 100755
  
 -emacs --batch --no-site-file --load $PLEXIL_HOME/compilers/plexilisp/plexil.el $1 --eval '(plexil)'
 +emacs --batch --no-site-file --load $PLEXIL_HOME/plexilisp/plexil.el $1 --eval '(plexil)'
+diff --git a/scripts/plexiltest b/scripts/plexiltest
+index a5f7532..65e5d60 100755
+--- a/scripts/plexiltest
++++ b/scripts/plexiltest
+@@ -28,13 +28,11 @@
+ if [ -z "$PLEXIL_HOME" ]
+ then
+     echo Error: Please set environment variable PLEXIL_HOME
+-    echo to the full pathname of your 'plexil' or 'trunk' directory.
++    echo by loading /etc/profile.d/plexil.sh.
+     echo Exiting.
+     exit 1
+ fi
+ 
+-. $PLEXIL_HOME/scripts/plexil-setup.sh
+-
+ validate_file()
+ {
+     if [ -z $1 ]
+@@ -168,9 +166,9 @@ help_text="Options:\n\
+ if [ $PLEXIL_EXECUTABLE ]
+ then
+     prog=$PLEXIL_EXECUTABLE
+-elif [ -f $PLEXIL_HOME/bin/TestExec ] &&  [ -x $PLEXIL_HOME/bin/TestExec ]
++elif [ -f /usr/bin/plexil-TestExec ] &&  [ -x /usr/bin/plexil-TestExec ]
+ then
+-    prog=$PLEXIL_HOME/bin/TestExec
++    prog=/usr/bin/plexil-TestExec
+ elif [ -f $PLEXIL_HOME/src/apps/TestExec/TestExec ] && [ -x $PLEXIL_HOME/src/apps/TestExec/TestExec ]
+ then
+     prog=$PLEXIL_HOME/src/apps/TestExec/TestExec
+@@ -330,7 +328,7 @@ then
+         # Check local port, if supplied
+         if [ -n "$port_in" ]
+         then
+-            if ( echo `list_ports_in_use` | grep -q -v "\<${port_in}\>" )
++            if ( echo `$PLEXIL_HOME/scripts/list_ports_in_use` | grep -q -v "\<${port_in}\>" )
+             then
+                 echo "Error: No Viewer is listening on local port $port_in. Exiting."
+                 exit 1
+@@ -360,7 +358,7 @@ else
+             exit 1
+         fi
+         port_cmd="-n $port_in"
+-    elif ( echo `list_ports_in_use` | grep -q "\<${port_in}\>" )
++    elif ( echo `$PLEXIL_HOME/scripts/list_ports_in_use` | grep -q "\<${port_in}\>" )
+     then
+         echo "Error: Port $port_in is in use. Exiting."
+         exit 1
+diff --git a/scripts/summarize-plexil b/scripts/summarize-plexil
+index b83f30a..f9e4217 100755
+--- a/scripts/summarize-plexil
++++ b/scripts/summarize-plexil
+@@ -37,7 +37,7 @@ usage="summarize-plexil input-file [ result-file ] [ transform-file ]"
+ if [ -z "$PLEXIL_HOME" ]
+   then
+     echo Please set environment variable PLEXIL_HOME
+-    echo to the absolute pathname of your 'plexil' directory.
++    echo by loading /etc/profile.d/plexil.sh.
+     exit 1
+ fi
+ 
+@@ -47,7 +47,7 @@ transform_file="$PLEXIL_HOME/schema/summarize-plexil.xsl"
+ result_file="summary.txt"
+ 
+ # Location of the Saxon XSLT processor
+-saxon_jar="$PLEXIL_HOME/jars/saxon9he.jar"
++saxon_jar=/usr/share/java/saxon/Saxon-HE.jar
+  
+ # Determine argument values, overriding defaults when specified.
+ 
+@@ -68,11 +68,7 @@ if [ $# = 3 ]
+     exit 1
+ fi
+ 
+-JAVA=java
+-if [ -n "$JAVA_HOME" ]
+-then
+-    JAVA=$JAVA_HOME/bin/java
+-fi
++JAVA=/usr/bin/java
+ 
+ echo "Summarizing $input_file ..."
+ $JAVA -jar $saxon_jar -o:$result_file $input_file $transform_file 
